services:
  - type: web
    name: shr-n8n-prod
    runtime: docker
    dockerfilePath: n8n/Dockerfile
    plan: free
    envVars:
      - key: N8N_PORT
        value: 10000  # Render prefiere el 10000 o el que diga $PORT
      - key: N8N_HOST
        value: 0.0.0.0
      - key: N8N_PROTOCOL
        value: https
      - key: NODE_OPTIONS
        value: "--max-old-space-size=400"
      - key: N8N_METRICS
        value: "false"
      - key: N8N_ENCRYPTION_KEY
        generateValue: true
