FROM docker.n8n.io/n8nio/n8n:latest

# Configurar zona horaria y optimización de memoria
ENV TZ=America/Bogota
ENV NODE_OPTIONS="--max-old-space-size=400"

# No se pone CMD para dejar que el entrypoint oficial de n8n haga su trabajo
