"""initial_schema_v2_organizacional

Revision ID: aaaec599808c
Revises: 
Create Date: 2026-05-13 01:57:30.610767

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'aaaec599808c'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('areas', sa.Column('proceso_id', sa.Integer(), nullable=True))
    op.add_column('areas', sa.Column('descripcion', sa.Text(), nullable=True))
    op.add_column('areas', sa.Column('objetivo', sa.Text(), nullable=True))
    op.add_column('areas', sa.Column('responsable', sa.String(), nullable=True))
    op.add_column('areas', sa.Column('estado', sa.String(), nullable=True))
    op.add_column('areas', sa.Column('updated_at', sa.DateTime(timezone=True), nullable=True))
    op.add_column('areas', sa.Column('deleted_at', sa.DateTime(timezone=True), nullable=True))
    op.create_foreign_key(None, 'areas', 'procesos', ['proceso_id'], ['id'])
    op.add_column('empresas', sa.Column('grupo_empresarial_id', sa.Integer(), nullable=True))
    op.add_column('empresas', sa.Column('subsector', sa.String(), nullable=True))
    op.add_column('empresas', sa.Column('tamano_empresa', sa.String(), nullable=True))
    op.add_column('empresas', sa.Column('descripcion_negocio', sa.Text(), nullable=True))
    op.add_column('empresas', sa.Column('modelo_operativo', sa.Text(), nullable=True))
    op.add_column('empresas', sa.Column('cadena_valor', sa.Text(), nullable=True))
    op.add_column('empresas', sa.Column('ingresos_aproximados', sa.Float(), nullable=True))
    op.add_column('empresas', sa.Column('tipos_contratos', sa.Text(), nullable=True))
    op.add_column('empresas', sa.Column('distribucion_contratos', sa.Text(), nullable=True))
    op.add_column('empresas', sa.Column('estado', sa.String(), nullable=True))
    op.add_column('empresas', sa.Column('updated_at', sa.DateTime(timezone=True), nullable=True))
    op.add_column('empresas', sa.Column('deleted_at', sa.DateTime(timezone=True), nullable=True))
    op.create_foreign_key(None, 'empresas', 'grupos_empresariales', ['grupo_empresarial_id'], ['id'])
    op.add_column('homologaciones', sa.Column('observaciones_analista', sa.Text(), nullable=True))
    op.add_column('homologaciones', sa.Column('busqueda_internet_url', sa.String(), nullable=True))
    op.add_column('homologaciones', sa.Column('estado_busqueda', sa.String(), nullable=True))
    op.add_column('regionales', sa.Column('empresa_id', sa.Integer(), nullable=True))
    op.add_column('regionales', sa.Column('responsable', sa.String(), nullable=True))
    op.add_column('regionales', sa.Column('estado', sa.String(), nullable=True))
    op.add_column('regionales', sa.Column('updated_at', sa.DateTime(timezone=True), nullable=True))
    op.add_column('regionales', sa.Column('deleted_at', sa.DateTime(timezone=True), nullable=True))
    op.create_foreign_key(None, 'regionales', 'empresas', ['empresa_id'], ['id'])
    op.add_column('sedes', sa.Column('pais', sa.String(), nullable=True))
    op.add_column('sedes', sa.Column('cantidad_empleados', sa.Integer(), nullable=True))
    op.add_column('sedes', sa.Column('estado', sa.String(), nullable=True))
    op.add_column('sedes', sa.Column('updated_at', sa.DateTime(timezone=True), nullable=True))
    op.add_column('sedes', sa.Column('deleted_at', sa.DateTime(timezone=True), nullable=True))
    op.add_column('valoraciones', sa.Column('justificacion_ia', sa.Text(), nullable=True))
    op.add_column('valoraciones', sa.Column('editado_manual', sa.Boolean(), nullable=True))
    op.add_column('valoraciones', sa.Column('basico', sa.Float(), nullable=True))
    op.add_column('valoraciones', sa.Column('real_pagado', sa.Float(), nullable=True))
    op.add_column('valoraciones', sa.Column('garantizado', sa.Float(), nullable=True))
    op.add_column('valoraciones', sa.Column('garantizado_variable', sa.Float(), nullable=True))
    op.add_column('valoraciones', sa.Column('compensacion_total', sa.Float(), nullable=True))
    op.add_column('valoraciones', sa.Column('punto_medio_referencia', sa.Float(), nullable=True))
    op.add_column('valoraciones', sa.Column('posicion_equidad_pct', sa.Float(), nullable=True))
    op.drop_column('valoraciones', 'creado_manual')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('valoraciones', sa.Column('creado_manual', sa.BOOLEAN(), nullable=True))
    op.drop_column('valoraciones', 'posicion_equidad_pct')
    op.drop_column('valoraciones', 'punto_medio_referencia')
    op.drop_column('valoraciones', 'compensacion_total')
    op.drop_column('valoraciones', 'garantizado_variable')
    op.drop_column('valoraciones', 'garantizado')
    op.drop_column('valoraciones', 'real_pagado')
    op.drop_column('valoraciones', 'basico')
    op.drop_column('valoraciones', 'editado_manual')
    op.drop_column('valoraciones', 'justificacion_ia')
    op.drop_column('sedes', 'deleted_at')
    op.drop_column('sedes', 'updated_at')
    op.drop_column('sedes', 'estado')
    op.drop_column('sedes', 'cantidad_empleados')
    op.drop_column('sedes', 'pais')
    op.drop_constraint(None, 'regionales', type_='foreignkey')
    op.drop_column('regionales', 'deleted_at')
    op.drop_column('regionales', 'updated_at')
    op.drop_column('regionales', 'estado')
    op.drop_column('regionales', 'responsable')
    op.drop_column('regionales', 'empresa_id')
    op.drop_column('homologaciones', 'estado_busqueda')
    op.drop_column('homologaciones', 'busqueda_internet_url')
    op.drop_column('homologaciones', 'observaciones_analista')
    op.drop_constraint(None, 'empresas', type_='foreignkey')
    op.drop_column('empresas', 'deleted_at')
    op.drop_column('empresas', 'updated_at')
    op.drop_column('empresas', 'estado')
    op.drop_column('empresas', 'distribucion_contratos')
    op.drop_column('empresas', 'tipos_contratos')
    op.drop_column('empresas', 'ingresos_aproximados')
    op.drop_column('empresas', 'cadena_valor')
    op.drop_column('empresas', 'modelo_operativo')
    op.drop_column('empresas', 'descripcion_negocio')
    op.drop_column('empresas', 'tamano_empresa')
    op.drop_column('empresas', 'subsector')
    op.drop_column('empresas', 'grupo_empresarial_id')
    op.drop_constraint(None, 'areas', type_='foreignkey')
    op.drop_column('areas', 'deleted_at')
    op.drop_column('areas', 'updated_at')
    op.drop_column('areas', 'estado')
    op.drop_column('areas', 'responsable')
    op.drop_column('areas', 'objetivo')
    op.drop_column('areas', 'descripcion')
    op.drop_column('areas', 'proceso_id')
    # ### end Alembic commands ###
